config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users

  root 'home#home'

  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  match '/signin' => 'sessions#new', :as => :signin, via: [:get, :post]

  delete 'users/destroy/' => 'users#destroy', as: 'destroy_admin_user_session'

  get 'category/:id/' => 'categories#show', as: 'category'
  get 'topic/:id/' => 'topics#show', as: 'topic'
  get 'users/ban/:id/' => 'users#ban', as: 'ban_user'
  resources :posts
  resources :users

  get 'posts/:post_id/comments' => 'comments#index', as: 'post_comments'
  post 'posts/:post_id/comments' => 'comments#create'
  get 'posts/:post_id/comments/new' => 'comments#new', as: 'new_post_comment'
  get 'posts/:post_id/comments/:id/edit' => 'comments#edit', as: 'edit_post_comment'
  get 'posts/:post_id/comments/:id' => 'comments#show', as: 'post_comment'
  patch 'posts/:post_id/comments/:id' => 'comments#update'
  put 'posts/:post_id/comments/:id' => 'comments#update'
  delete 'posts/:post_id/comments/:id' => 'comments#destroy'

  get 'topic/:topic_id/posts' => 'posts#index', as: 'topic_posts'
  post 'topic/:topic_id/posts' => 'posts#create'
  get 'topic/:topic_id/posts/new' => 'posts#new', as: 'new_topic_post'
  get 'topic/:topic_id/posts/:id/edit' => 'posts#edit', as: 'edit_topic_post'
  get 'topic/:topic_id/posts/:id' => 'posts#show', as: 'topic_post'
  patch 'topic/:topic_id/posts/:id' => 'posts#update'
  put 'topic/:topic_id/posts/:id' => 'posts#update'
  delete 'topic/:topic_id/posts/:id' => 'posts#destroy'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
	belongs_to :category
  has_many :topics
  has_many :posts

	def all_posts
    if self.topics
			return Post.where('topic_id IN (?) OR id IN (?)', self.topics.map(&:id), self.posts.map(&:id))
		end
		Post.where(id: self.posts.map(&:id))
	end

	def get_topic
		if self.topic_id
			return Topic.find(self.topic_id)
		end
		nil
	end

	def get_views
		self.all_posts.sum(:views)
	end

	def get_comments
		Comment.where(post_id: self.all_posts.map(&:id))
	end

	def last_post
    self.all_posts.order('updated_at').last
	end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def show
    @topic = Topic.find(params[:id])
    @posts = @topic.posts(:order => 'featured, updated_at DESC').page(params[:page]).per(10)
    if !current_user && @topic.logged
      redirect_to new_user_registration_path
    end

  end

  # def create
  #   @topic = Topic.new(topics_params)
  #   if @topic.save
  #     redirect_to topic_path(@topic.id)
  #   else
  #     render 'new'
  #   end
  # end
  #
  # def new
  #   @topic = Topic.new
  # end
  #
  # private
  # def topics_params
  #   params.require(:topic).permit(:name, :category_id, :topic_id, :description)
  # end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/new.html.erb
<% if @topic.errors.any? %>
<div class="row">
    <div class="col-lg-12">
        <div class="alert alert-danger alert-dismissable">
          <ul>
            <% @topic.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    </div>
</div>
<% end %>

<%= form_for @topic do |f| %>
<div class="row">
  <div class="panel panel-info">
    <div class="panel-heading">
      New Topic
    </div>
      <div class="panel-body">

        <p>
          Category: <%= f.select :category_id, options_for_select(Category.all.map{|s|[s.name, s.id]}) %>
        </p>
        <p>
          Fórum: <%= f.select :topic_id, options_for_select(Topic.where(topic_id: nil).map{|s|[s.name, s.id]}) %>
        </p>
        <p>
          Title: <%= f.text_field :name %>
        </p>
        <p>
          Description: <%= f.text_area :description %>
        </p>
        <p>
          Logged: <%= f.check_box :logged %>
        </p>
        <div class="actions">
          <input type="submit" class="btn btn-success" value="Salvar">
        </div>
      </div>

  </div>
</div>
<% end %>

app/views/topics/show.html.erb
<div class="row">
  <ol class="breadcrumb">
    <li><a href="<%= root_url %>">Home</a></li>
    <li><a href="<%= category_path(@topic.category.id) %>"><%= @topic.category.name %></a></li>
    <% if @topic.get_topic == nil %>
      <li><a href="<%= topic_path(@topic.id) %>" class="active"><%= @topic.name %></a></li>
    <% else %>
      <li><a href="<%= topic_path(@topic.get_topic.id) %>"><%= @topic.get_topic.name %></a></li>
      <li><a href="<%= topic_path(@topic.id) %>" class="active"><%= @topic.name %></a></li>
    <% end %>
  </ol>
</div>

<% if current_user and !current_user.block %>
<div class="row pd10">
  <a href="<%= new_topic_post_path(@topic.id) %>" class="btn btn-info">New Topic</a>
</div>
<% end %>

<% if @topic.topics.count > 0 %>
<div class="row">
  <div class="panel panel-info">
    <div class="panel-heading col-md-12">
      <table width="100%">
        <tr>
          <td class="col-md-6">Forum</td>
          <td class="col-md-2">Tópicos/Posts</td>
          <td class="col-md-4">Últimos posts</td>
        </tr>
      </table>
    </div>
    <% @topic.topics.each do |topic| %>
    <% if topic %>
    <table class="table" width="100%">
      <tr>
        <td class="col-md-6">
          <p><a href="<%= topic_path(topic.id) %>"><%= topic.name %></a> <small>(<%= topic.get_views %> Viewing)</small></p>
          <p><small><%= topic.description %></small></p>
        </td>
        <td class="col-md-2">
          <p>
            Threads: <%= topic.posts.count %>
          </p>
          <p>
            Posts: <%= topic.get_comments.count %>
          </p>
        </td>
        <td class="col-md-4">
          <% if topic.last_post %>
          <p>
            <a href="<%= topic_path(topic.id) %>"><%= topic.last_post.name %></a> Go to last post by <a href="<%= user_path(topic.last_post.user.id) %>"><%= topic.last_post.user.name %></a>
          </p>
          <p>
            <%= topic.last_post.updated_at %>
          </p>
          <% else %>
          <p>
            -
          </p>
          <% end %>
        </td>
      </tr>
    </table>
    <% end %>
    <% end %>
  </div>
</div>
<% end %>

<div class="row">&nbsp;</div>

<div class="row">
  <div class="panel panel-info">
    <div class="panel-heading col-md-12">
      <table width="100%">
        <tr>
          <td class="col-md-6">Posts</td>
          <td class="col-md-2">Tópicos/Posts</td>
          <td class="col-md-4">Últimos posts</td>
        </tr>
      </table>
    </div>
    <% @posts.each do |p| %>
    <table class="table <% if p.featured %>navbar-default<% end %>" width="100%">
      <tr>
        <td class="col-md-6">
          <a href="<%= post_path(p.id) %>"><%= p.name %></a>
        </td>
        <td class="col-md-2">
            <p>Replies: <%= p.get_replies_count %></p>
            <p>Views: <%= p.views %></p>
        </td>
        <td class="col-md-4">
            <p><%= p.user.name %></p>
            <p><%= p.updated_at %></p>
        </td>
      </tr>
    </table>
    <% end %>
    <%= paginate @posts %>
  </div>
</div>