config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users

  root 'home#home'

  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  match '/signin' => 'sessions#new', :as => :signin, via: [:get, :post]

  delete 'users/destroy/' => 'users#destroy', as: 'destroy_admin_user_session'

  get 'category/:id/' => 'categories#show', as: 'category'
  get 'topic/:id/' => 'topics#show', as: 'topic'
  get 'users/ban/:id/' => 'users#ban', as: 'ban_user'
  resources :posts
  resources :users

  get 'posts/:post_id/comments' => 'comments#index', as: 'post_comments'
  post 'posts/:post_id/comments' => 'comments#create'
  get 'posts/:post_id/comments/new' => 'comments#new', as: 'new_post_comment'
  get 'posts/:post_id/comments/:id/edit' => 'comments#edit', as: 'edit_post_comment'
  get 'posts/:post_id/comments/:id' => 'comments#show', as: 'post_comment'
  patch 'posts/:post_id/comments/:id' => 'comments#update'
  put 'posts/:post_id/comments/:id' => 'comments#update'
  delete 'posts/:post_id/comments/:id' => 'comments#destroy'

  get 'topic/:topic_id/posts' => 'posts#index', as: 'topic_posts'
  post 'topic/:topic_id/posts' => 'posts#create'
  get 'topic/:topic_id/posts/new' => 'posts#new', as: 'new_topic_post'
  get 'topic/:topic_id/posts/:id/edit' => 'posts#edit', as: 'edit_topic_post'
  get 'topic/:topic_id/posts/:id' => 'posts#show', as: 'topic_post'
  patch 'topic/:topic_id/posts/:id' => 'posts#update'
  put 'topic/:topic_id/posts/:id' => 'posts#update'
  delete 'topic/:topic_id/posts/:id' => 'posts#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base

  validate :name_required

  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments

  PERMISSIONS = [["Administrador", 1], ["Moderador", 2], ["Usuário", 3]]

  def is_admin?
    self.permission == 1
  end

  def is_moderator?
    self.permission == 2
  end

  def get_user_permission
    PERMISSIONS[self.permission - 1] ? PERMISSIONS[self.permission - 1][0] : 'Não encontrado'
  end

  def image
    url = Gravatar.new(self.email).image_url
  end

  def img
    "<img src='#{Gravatar.new(self.email).image_url}' />".html_safe
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  private
  def name_required
    if name == ""
      errors[:base] << "Name can't be blank"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.page(params[:page]).per(9)
  end

  def destroy
    redirect_to destroy_user_session_path
  end

  def ban
    if current_user.is_admin? or current_user.is_moderator?
      @user = User.find(params[:id])
      @user.block = !@user.block
      @user.save
    end
    redirect_to user_path(params[:id])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order('updated_at DESC').page(params[:page]).per(10)
    @post_comments = @user.comments.order('updated_at DESC').page(params[:page]).per(10)
    # @post_comments = @user.comments.select(:post_id).distinct.order('updated_at DESC').page(params[:page]).per(10)
  end

  def create
    @user = User.new(users_params)
    @user.permission = false
    @user.block = false
    if @user.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def new
    @user = User.new
  end

  private
  def users_params
    params.require(:user).permit(:name, :email, :block, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="row">
  <ol class="breadcrumb">
    <li><a href="<%= root_url %>">Home</a></li>
    <li><a href="<%= users_path %>" class="active">Users</a></li>
  </ol>
</div>

<div class="row">
  <div class="panel panel-default">
    <div class="row">
      <% @users.each do |u| %>
      <div class="col-lg-3">
        <div class="panel-body">
          <p align="center">
            <a href="<%= user_path(u.id) %>"><img src="<%= u.image %>" class="image"></a>
          </p>
          <p align="center">
            <a href="<%= user_path(u.id) %>"><%= u.name %></a>
          </p>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<% if @user.errors.any? %>
<div class="row">
    <div class="col-lg-12">
        <div class="alert alert-danger alert-dismissable">
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    </div>
</div>
<% end %>

<%= form_for @user do |f| %>
<div class="row">
  <div class="panel panel-info">
    <div class="panel-heading">
      New account
    </div>
      <div class="panel-body">
        <p>
          Name: <%= f.text_field :name %>
        </p>
        <p>
          Email: <%= f.text_field :email %>
        </p>
        <p>
          Password: <%= f.password_field :password %>
        </p>
        <p>
          Password Confirmation: <%= f.password_field :password_confirmation %>
        </p>
        <div class="actions">
          <input type="submit" class="btn btn-success" value="Salvar">
        </div>
      </div>

  </div>
</div>
<% end %>

app/views/users/show.html.erb
<div class="row">
  <ol class="breadcrumb">
    <li><a href="<%= root_url %>">Home</a></li>
    <li><a href="<%= users_path %>">Users</a></li>
    <li><a href="<%= user_path(@user.id) %>" class="active"><%= @user.name %></a></li>
  </ol>
</div>

<div class="row">
  <div class="panel panel-default">
    <div class="row">
      <div class="panel-body">
        <div class="col-lg-4">
          <div align="center">
            <img src="<%= @user.image %>" class="image">
          </div>
          <div align="center" style="padding-top:20px;">
            <b>Name:</b> <%= @user.name %><BR>
            <b>Email:</b> <%= @user.email %><BR>
            <b>Created:</b> <%= @user.created_at %><BR>
            <% if permission? %>
              <% if @user.block %>
                <a href="<%= ban_user_path(@user.id) %>" class="btn btn-success">UNBLOCK</a>
              <% else %>
                <a href="<%= ban_user_path(@user.id) %>" class="btn btn-danger">BLOCK</a>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="col-lg-4">
          <div class="panel-body">
            <p>
              <b>My Last Topics</b>
            </p>
            <% if @posts.count == 0 %>
            <p>
              No topic.
            </p>
            <% end %>
            <% @posts.each do |p| %>
              <p>
                <a href="<%= post_path(p.id) %>"><%= p.name %></a> - <%= p.updated_at %>
              </p>
            <% end %>
            <!-- <%= paginate @posts %> -->
          </div>
        </div>
        <div class="col-lg-4">
          <div class="panel-body">
            <p>
              <b>My Last Posts</b>
            </p>
            <% if @post_comments.count == 0 %>
            <p>
              No post.
            </p>
            <% end %>
            <% @post_comments.each do |p| %>
            <% if p.post %>
              <p>
                <a href="<%= post_path(p.post_id) %>#<%= p.id %>"><%= p.post.name %></a> - <%= p.post.updated_at %>
              </p>
            <% end %>
            <% end %>
            <!-- <%= paginate @post_comments %> -->
          </div>
        </div>
      </div>
    </div>
  </div>
</div>