config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users

  root 'home#home'

  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  match '/signin' => 'sessions#new', :as => :signin, via: [:get, :post]

  delete 'users/destroy/' => 'users#destroy', as: 'destroy_admin_user_session'

  get 'category/:id/' => 'categories#show', as: 'category'
  get 'topic/:id/' => 'topics#show', as: 'topic'
  get 'users/ban/:id/' => 'users#ban', as: 'ban_user'
  resources :posts
  resources :users

  get 'posts/:post_id/comments' => 'comments#index', as: 'post_comments'
  post 'posts/:post_id/comments' => 'comments#create'
  get 'posts/:post_id/comments/new' => 'comments#new', as: 'new_post_comment'
  get 'posts/:post_id/comments/:id/edit' => 'comments#edit', as: 'edit_post_comment'
  get 'posts/:post_id/comments/:id' => 'comments#show', as: 'post_comment'
  patch 'posts/:post_id/comments/:id' => 'comments#update'
  put 'posts/:post_id/comments/:id' => 'comments#update'
  delete 'posts/:post_id/comments/:id' => 'comments#destroy'

  get 'topic/:topic_id/posts' => 'posts#index', as: 'topic_posts'
  post 'topic/:topic_id/posts' => 'posts#create'
  get 'topic/:topic_id/posts/new' => 'posts#new', as: 'new_topic_post'
  get 'topic/:topic_id/posts/:id/edit' => 'posts#edit', as: 'edit_topic_post'
  get 'topic/:topic_id/posts/:id' => 'posts#show', as: 'topic_post'
  patch 'topic/:topic_id/posts/:id' => 'posts#update'
  put 'topic/:topic_id/posts/:id' => 'posts#update'
  delete 'topic/:topic_id/posts/:id' => 'posts#destroy'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
    @categories = Category.all
    @user = User.new
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/home.html.erb
<div class="row">
  <div class="panel panel-info">
    <% @categories.each do |category| %>
    <div class="panel-heading col-md-12">
      <table width="100%">
        <tr>
          <td class="col-md-6"><a href="<%= category_path(category.id) %>"><%= category.name %></a></td>
          <td class="col-md-2">Threads/Posts</td>
          <td class="col-md-4">Last posts</td>
        </tr>
      </table>
    </div>
    <% category.tops.each do |topic| %>
    <% if topic %>
    <table class="table" width="100%">
      <tr>
        <td class="col-md-6">
          <p><a href="<%= topic_path(topic.id) %>"><%= topic.name %></a> <small>(<%= topic.get_views %> Viewing)</small></p>

          <p><small><%= topic.description %></small></p>

            <p>Sub-Forums:</p>
            <% topic.topics.each do |t| %>
            <small><a href="<%= topic_path(t.id) %>"><%= t.name %></a></small><BR>
          <% end %>
        </td>
        <td class="col-md-2">
          <p>
            Threads: <%= topic.all_posts.count %>
          </p>
          <p>
            Posts: <%= topic.get_comments.count %>
          </p>
        </td>
        <td class="col-md-4">
          <% if topic.last_post %>
          <p><a href="<%= post_path(topic.last_post.id) %>"><%= truncate(topic.last_post.name, :length => 30) %></a> Go to last post by <a href="<%= user_path(topic.last_post.user.id) %>"><%= topic.last_post.user.name %></a></p>
          <%= topic.last_post.updated_at %>
          <% else %>
          -
          <% end %>
        </td>
      </tr>
    </table>
    <% end %>
    <% end %>
    <% end %>
  </div>
</div>