config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users

  root 'home#home'

  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  match '/signin' => 'sessions#new', :as => :signin, via: [:get, :post]

  delete 'users/destroy/' => 'users#destroy', as: 'destroy_admin_user_session'

  get 'category/:id/' => 'categories#show', as: 'category'
  get 'topic/:id/' => 'topics#show', as: 'topic'
  get 'users/ban/:id/' => 'users#ban', as: 'ban_user'
  resources :posts
  resources :users

  get 'posts/:post_id/comments' => 'comments#index', as: 'post_comments'
  post 'posts/:post_id/comments' => 'comments#create'
  get 'posts/:post_id/comments/new' => 'comments#new', as: 'new_post_comment'
  get 'posts/:post_id/comments/:id/edit' => 'comments#edit', as: 'edit_post_comment'
  get 'posts/:post_id/comments/:id' => 'comments#show', as: 'post_comment'
  patch 'posts/:post_id/comments/:id' => 'comments#update'
  put 'posts/:post_id/comments/:id' => 'comments#update'
  delete 'posts/:post_id/comments/:id' => 'comments#destroy'

  get 'topic/:topic_id/posts' => 'posts#index', as: 'topic_posts'
  post 'topic/:topic_id/posts' => 'posts#create'
  get 'topic/:topic_id/posts/new' => 'posts#new', as: 'new_topic_post'
  get 'topic/:topic_id/posts/:id/edit' => 'posts#edit', as: 'edit_topic_post'
  get 'topic/:topic_id/posts/:id' => 'posts#show', as: 'topic_post'
  patch 'topic/:topic_id/posts/:id' => 'posts#update'
  put 'topic/:topic_id/posts/:id' => 'posts#update'
  delete 'topic/:topic_id/posts/:id' => 'posts#destroy'

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	belongs_to :topic
	validate :text_required

	has_many :comments, :dependent => :delete_all
	accepts_nested_attributes_for :comments

  def coment
    super
  end

	def get_replies_count
		quantity =  self.comments.count - 1
		if quantity < 0
			return 0
		end
		quantity
	end

	private
  def text_required
    if name == ""
      errors[:base] << "Name can't be blank"
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :topic, only: [:new, :create]
  before_action :user, only: [:edit, :update, :destroy]

  def topic
    if !Topic.find_by_id(params[:topic_id])
      redirect_to root_url
    end
  end

  def user
    @post = Post.find(params[:id])
    if !current_user == @post.user
      redirect_to post_path(@post.post_id)
    end
  end

  def show
    @post = Post.find(params[:id])
    if !current_user && @post.logged
      redirect_to new_user_registration_path
    end

    if @post.views == nil
      @post.views = 0
    end
    @post.views += 1
    @post.save

    @comments = @post.comments.page(params[:page]).per(10)
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = Post.new(posts_params)
    @post.topic_id = params[:topic_id]

    if current_user.is_admin?
      @post.comments.first.user_id = @post.user_id
    else
      @post.comments.first.user_id = current_user.id
      @post.user_id = current_user.id
      @post.featured = false
    end

    if @post.save
      redirect_to post_path(@post.id)
    else
      render 'new'
    end
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
    1.times do
      comment = @post.comments.build
    end
  end

private
  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(posts_params)
      redirect_to post_path(@post.id)
    else
      render 'edit'
    end
  end

  def destroy
    Post.destroy(params[:id])
    redirect_to root_url
  end

  private
  def posts_params
    params.require(:post).permit(:name, :featured, :topic_id, :user_id, comments_attributes: [:content])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="row">
  <ol class="breadcrumb">
    <li><a href="<%= root_url %>">Home</a></li>
    <li><a href="<%= category_path(@post.topic.category.id) %>"><%= @post.topic.category.name %></a></li>
    <% if @post.topic.get_topic == nil %>
      <li><a href="<%= topic_path(@post.topic.id) %>"><%= @post.topic.name %></a></li>
    <% else %>
      <li><a href="<%= topic_path(@post.topic.get_topic.id) %>"><%= @post.topic.get_topic.name %></a></li>
      <li><a href="<%= post_path(@post.topic.id) %>"><%= @post.topic.name %></a></li>
    <% end %>
    <li><a href="<%= post_path(@post.id) %>" class="active"><%= @post.name %></a></li>
  </ol>
</div>

<% if @post.errors.any? %>
<div class="row">
    <div class="col-lg-12">
        <div class="alert alert-danger alert-dismissable">
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    </div>
</div>
<% end %>

<%= form_for @post do |f| %>
<div class="row">
  <div class="panel panel-info">
    <div class="panel-heading">
      Edit
    </div>
      <div class="panel-body">
        <p>
          Title: <%= f.text_field :name %>
        </p>
        <p>
          Featured: <%= f.check_box :featured %>
        </p>
        <div class="actions">
          <input type="submit" class="btn btn-success" value="Salvar">
        </div>
      </div>

  </div>
</div>
<% end %>

app/views/posts/new.html.erb
<div class="row">
  <ol class="breadcrumb">
    <li><a href="<%= root_url %>">Home</a></li>
    <li><a href="<%= category_path(@topic.category.id) %>"><%= @topic.category.name %></a></li>
    <% if @topic.get_topic == nil %>
      <li><a href="<%= topic_path(@topic.id) %>"><%= @topic.name %></a></li>
    <% else %>
      <li><a href="<%= topic_path(@topic.get_topic.id) %>"><%= @topic.get_topic.name %></a></li>
      <li><a href="<%= topic_path(@topic.id) %>"><%= @topic.name %></a></li>
    <% end %>
  </ol>
</div>

<% if @post.errors.any? %>
<div class="row">
    <div class="col-lg-12">
        <div class="alert alert-danger alert-dismissable">
          <ul>
            <% @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    </div>
</div>
<% end %>

<%= form_for @post, url: topic_posts_path(@topic.id) do |f| %>
<div class="row">
  <div class="panel panel-info">
    <div class="panel-heading">
      New Topic
    </div>
      <div class="panel-body">
        <% if current_user.is_admin? %>
        <p>
          User: <%= f.select :user_id, options_for_select(User.all.map{|s|[s.name, s.id]}) %>
        </p>
        <p>
          Featured: <%= f.check_box :featured %>
        </p>
        <% end %>
        <p>
          Title: <%= f.text_field :name %>
        </p>
        <%= f.fields_for :comments do |ff| %>
          <p>
            <%= ff.label :content, "Description" %>:
            <%= ff.text_area :content, :rows => 3 %>
          </p>
        <% end %>
        <div class="actions">
          <input type="submit" class="btn btn-success" value="Salvar">
        </div>
      </div>

  </div>
</div>
<% end %>

app/views/posts/show.html.erb
<div class="row">
  <ol class="breadcrumb">
    <li><a href="<%= root_url %>">Home</a></li>
    <li><a href="<%= category_path(@post.topic.category.id) %>"><%= @post.topic.category.name %></a></li>
    <% if @post.topic.get_topic == nil %>
      <li><a href="<%= topic_path(@post.topic.id) %>"><%= @post.topic.name %></a></li>
    <% else %>
      <li><a href="<%= topic_path(@post.topic.get_topic.id) %>"><%= @post.topic.get_topic.name %></a></li>
      <li><a href="<%= topic_path(@post.topic.id) %>"><%= @post.topic.name %></a></li>
    <% end %>
    <li><a href="<%= post_path(@post.id) %>" class="active"><%= @post.name %></a></li>
  </ol>
</div>

<div class="row">
  <div class="panel panel-info">
    <div class="panel-heading col-md-12">
      <h5 style="float:left"><%= @post.name %> - views <%= @post.views %></h5>
      <% if permission? or @post.user == current_user and !current_user.block %>
        <span style="float:right">
        <%= link_to 'Edit', edit_post_path(@post.id), class: "btn btn-info" %>
        <%= link_to 'Delete', post_path(@post.id), class: "btn btn-info", method: :delete, data: { confirm: "Tem certeza que deseja excluir?" } %></span>
      <% end %>
    </div>
    <% @comments.each_with_index do |comment, i| %>
    <div class="panel-body border">
      <a name="<%= comment.id %>"></a>
      <div>&nbsp;</div>
      <div>&nbsp;</div>
      <p>
        <a href="#<%= comment.id %>">#<%= i %></a>
        writed <b><a href="<%= user_path(comment.user.id) %>"><%= comment.user.name %></a></b> at <%= comment.created_at %>
        <% if permission? or comment.user == current_user and !current_user.block %>
        <span style="float:right">
        <% if !current_user.is_moderator? %><%= link_to 'Edit', edit_post_comment_path(@post.id, comment.id), class: "btn btn-info" %><% end %>
        <%= link_to 'Delete', post_comment_path(@post.id, comment.id), class: "btn btn-info", method: :delete, data: { confirm: "Tem certeza que deseja excluir?" } %></span>
        <% end %>
      </p>
      <%= simple_format comment.content %>
      <div>&nbsp;</div>
    </div>
    <% end %>
    <div class="panel-body">
      <%= paginate @comments %>
    </div>
    <% if current_user and !current_user.block %>
    <div class="panel-body">
      <a class="btn btn-info" href="<%= new_post_comment_path(@post.id) %>">New replie</a>
    </div>
    <% end %>
  </div>
</div>